#' NHDplus HR NA data frame
#'
#' Return a data frame with all the columns in the NHDplus HR REST service with
#' NAs. Columns 'OBJECTID', 'Shape', and 'Shape_Length' are not included.
#' Columns 'Measure', 'Snap_Lat', 'Snap_Long', and 'Snap_Distance' are added for
#' downstream binding.
#'
#' More info at at \url{https://hydro.nationalmap.gov/arcgis/rest/services/NHDPlus_HR/MapServer/2}.
#'

#' @export
nhdplushr_na <- function() {

  df <- data.frame(OBJECTID = NA_real_,
                   DNDRAINCOU = NA_real_,
                   QEMA = NA_real_,
                   STREAMLEVE = NA_real_,
                   FDATE = NA_real_,
                   REACHCODE = NA_character_,
                   LEVELPATHI = NA_real_,
                   QINCRCMA = NA_real_,
                   NHDPLUSID = NA_real_,
                   DNMINORHYD = NA_real_,
                   ARQNAVMA = NA_real_,
                   FTYPE = NA_real_,
                   GNIS_NAME = NA_character_,
                   PETMA = NA_real_,
                   QLOSSMA = NA_real_,
                   PATHLENGTH = NA_real_,
                   QINCRDMA = NA_real_,
                   RTNDIV = NA_real_,
                   GNIS_ID = NA_character_,
                   WBAREA_PERMANENT_IDENTIFIER = NA_character_,
                   RESOLUTION = NA_real_,
                   FLOWDIR = NA_real_,
                   LENGTHKM = NA_real_,
                   DNLEVEL = NA_real_,
                   FCODE = NA_real_,
                   QAMA = NA_real_,
                   DIVDASQKM = NA_real_,
                   VDMA = NA_real_,
                   VPUID = NA_character_,
                   MAINPATH = NA_real_,
                   STREAMCALC = NA_real_,
                   PERMANENT_IDENTIFIER = NA_character_,
                   VPUIN = NA_real_,
                   FROMNODE = NA_real_,
                   HYDROSEQ = NA_real_,
                   TERMINALPA = NA_real_,
                   TOMEAS = NA_real_,
                   ARBOLATESU = NA_real_,
                   STARTFLAG = NA_real_,
                   TOTDASQKM = NA_real_,
                   INNETWORK = NA_real_,
                   QCMA = NA_real_,
                   TERMINALFL = NA_real_,
                   UPLEVELPAT = NA_real_,
                   UPHYDROSEQ = NA_real_,
                   TONODE = NA_real_,
                   MAXELEVRAW = NA_real_,
                   DIVERGENCE = NA_real_,
                   FROMMEAS = NA_real_,
                   DNHYDROSEQ = NA_real_,
                   MINELEVRAW = NA_real_,
                   STREAMORDE = NA_real_,
                   QDMA = NA_real_,
                   VPUOUT = NA_real_,
                   DNLEVELPAT = NA_real_,
                   AREASQKM = NA_real_,
                   VISIBILITYFILTER = NA_real_,
                   MAXELEVSMO = NA_real_,
                   MINELEVSMO = NA_real_,
                   GAGEQMA = NA_real_,
                   SLOPE = NA_real_,
                   SLOPELENKM = NA_real_,
                   ELEVFIXED = NA_real_,
                   HWTYPE = NA_real_,
                   HWNODESQKM = NA_real_,
                   QINCRBMA = NA_real_,
                   VAMA = NA_real_,
                   QINCRAMA = NA_real_,
                   AVGQADJMA = NA_real_,
                   QBMA = NA_real_,
                   VBMA = NA_real_,
                   VCMA = NA_real_,
                   VEMA = NA_real_,
                   QINCREMA = NA_real_,
                   QFMA = NA_real_,
                   QINCRFMA = NA_real_,
                   QGADJMA = NA_real_,
                   QGNAVMA = NA_real_,
                   GAGEADJMA = NA_real_,
                   GAGEIDMA = NA_character_,
                   Shape_Length = NA_real_)
  return(df)
}


